### PR TITLE
Install/Upgrade to Server Density agent v2.

### PR DESCRIPTION
**Pull request by CorbanR**
- Upgrade logic.
- Options for official Server Density plugin installation.
- Updated syntax (yaml)

### CODE REVIEW

**Comment by carlosperello** [comment]
@CorbanR the PR has conflicts with our master branch, could you solve them so I may review it ?

Thank you!

**Comment by CorbanR** [comment]
@carlosperello  I'm not sure I am able to do that, with my current permissions to your branch. I "think" you may need to. I made quite a few updates / changes. 

Would it be best if I close this PR and maybe you can `git fetch upstream`?

**Comment by carlosperello** [comment]
@CorbanR As far as I know, the problem is that your branch is missing some updates we did in our repository after the initial fork. You need to merge those changes first or we need to send you a PR with our changes...

As the original author, and if you agree, we want to give you write access to this repository, so you are still able to review other PR and merge them and keep your branches inside this repository directly.

**Comment by CorbanR** [comment]
@carlosperello Yeah I'm totally cool with that. If you give me write access, I will cancel the pull request, and just fetch upstream, and fix any conflicts.

**Comment by carlosperello** [comment]
@CorbanR I just gave you write access.

I think the conflct you have in your PR is just the addition we did to send the provider and providerId fields in case of a cloud installation. If you add it to your v2 version that should be enough.

**Comment by bencer** [comment]
@CorbanR I've refactored the module implementing the cloud support that @carlosperello is asking here in a different way. I think would be cool to merge my branch that adds plenty other stuff:
- allow to overwrite an existing server
- generic plugin support
- and more things :)
https://github.com/bencer/ansible-serverdensity
example of use here: https://github.com/bencer/ansible-nginx-phpfpm-example/blob/master/vars_sd.yaml

Once we are all agree in this, we could improve the README/docs, add some tests and submit to Ansible Galaxy, what do you think?

**Comment by CorbanR** [comment]
@carlosperello I have fixed the merge conflict's \o/ and merged.

**Comment by CorbanR** [comment]
@bencer  I looked over your branch, and like some of the things I see. I don't agree with all of the changes, but it you submit a pull request to the upstream mater, It would be fun to get a dialog going. This would also allow me to make comments on particular portions of the code.

**Pull request merged**
